{% set version = "0.0.6" %}

package:
  name: asyncpg-listen
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/a/asyncpg-listen/asyncpg-listen-{{ version }}.tar.gz
    sha256: f3a889a3848903e4710705e785fd95940b3a5939a89a660827cdaaa113e1959e
  - folder: src
    url: https://github.com/anna-money/asyncpg-listen/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 4455a6c221deeca556ec5409fda4f62469fd89f76762136b0ff6ad8b78fa0241

build:
  script:
    - {{ PYTHON }} -c "p = __import__('pathlib').Path; p('dist/CHANGELOG.md').write_bytes(p('src/CHANGELOG.md').read_bytes())"
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - async-timeout >=3.0,<5.0
    - asyncpg >=0.27.0
    - python >=3.8

test:
  imports:
    - asyncpg_listen
  commands:
    - pip check
    - mypy -m asyncpg_listen
  requires:
    - pip
    - mypy

about:
  home: https://github.com/anna-money/asyncpg-listen
  summary: Helps to use PostgreSQL listen/notify with asyncpg
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
