{% set version = "0.0.7" %}
{% set COPY_FILES = ['CHANGELOG.md', 'asyncpg_listen/py.typed'] %}

package:
  name: asyncpg-listen
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/a/asyncpg-listen/asyncpg-listen-{{ version }}.tar.gz
    sha256: 33d8c6a69bb20139d143fd9e4035a4627ac76fbea4d874529f99fbb33f0596c5
  - folder: src
    url: https://github.com/anna-money/asyncpg-listen/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 79e148ddd6559ca46dfd1ed5989beaefe9743e8b0923b6aa2fbf798cf2404a1a

build:
  script:
    - {{ PYTHON }} -c "p = __import__('pathlib').Path; [p(f'dist/{f}').write_bytes(p(f'src/{f}').read_bytes()) for f in {{ COPY_FILES }}]"
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - async-timeout >=3.0,<5.0
    - asyncpg >=0.27.0
    - python >=3.8

test:
  imports:
    - asyncpg_listen
  commands:
    - pip check
    - mypy -m asyncpg_listen
  requires:
    - pip
    - mypy

about:
  home: https://github.com/anna-money/asyncpg-listen
  summary: Helps to use PostgreSQL listen/notify with asyncpg
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
