{% set python_min = "3.11" %}
{% set version = "0.0.8" %}
{% set COPY_FILES = ['CHANGELOG.md', 'asyncpg_listen/py.typed'] %}

package:
  name: asyncpg-listen
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/a/asyncpg-listen/asyncpg-listen-{{ version }}.tar.gz
    sha256: a2aea628a148ea016d9bcc5f80a5b9b0b56756d0ed76fdbc376ff50e238e493f
  - folder: src
    url: https://github.com/anna-money/asyncpg-listen/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7260843416b189d255b3cf626b66330fb7b1b1344fd2b90a805b6643290d9fdd

build:
  script:
    - {{ PYTHON }} -c "p = __import__('pathlib').Path; [p(f'dist/{f}').write_bytes(p(f'src/{f}').read_bytes()) for f in {{ COPY_FILES }}]"
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - asyncpg >=0.27.0
    - python >={{ python_min }}

test:
  imports:
    - asyncpg_listen
  commands:
    - pip check
    - mypy -m asyncpg_listen
  requires:
    - pip
    - mypy
    - python {{ python_min }}

about:
  home: https://github.com/anna-money/asyncpg-listen
  summary: Helps to use PostgreSQL listen/notify with asyncpg
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
